title: MIDJ.app Documentation
description: Documentation for MIDJ.app API
theme: just-the-docs

url: https://docs.midj.app

aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Reading Files
include:
  - _pages
  - _images

permalink: /:categories/:title/

#collections:
 # pages:
  #  permalink: "/"
   # output: true

color_scheme: dark

